### ISSUE TITLE
Question: J-J Dictionary Support?

### ISSUE THREAD

**Issue by mariomeissner** [migaku-official/Migaku-Dictionary-Addon#13]
Is there a way to load any J-J dictionaries (like sanseido or daijisen)?

**Comment by LucasMIA** [comment]
https://massimmersionapproach.com/table-of-contents/anki/mia-dictionary/

**Comment by LucasMIA** [comment]
Ask around the community if you actually need the Yomichan dictionary files themselves, I am sure you can find them easily.

**Comment by mariomeissner** [comment]
Sorry, my bad. As they are not officially listed in the [Yomichan Website](https://foosoft.net/projects/yomichan/index.html#dictionaries), I assumed they wouldn't exist. I did however just discover [this wonderful conversion tool](https://foosoft.net/projects/yomichan-import/) which lets me convert J-J's into the correct format. Thank you!
