### ISSUE TITLE
Daijirin dictionary is not working.

### ISSUE THREAD

**Issue by mariomeissner** [migaku-official/Migaku-Dictionary-Addon#14]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10 64Bit Anki 2.1.20

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
Daijirin (Sanseido) dictionary does not work. Others, like Daijisen, work without issues. I can import Daijirin, but when I search for words, no entries are displayed. This is what my `index.json` looks like:
```
{"title":"三省堂　スーパー大辞林","format":3,"revision":"daijirin1","sequenced":true}
```
And this is what the first few entries of `term_bank_1.json` look like:
```
[["あ","","","",0,["あ\n（１）五十音図ア行第一段の仮名。後舌の広母音。\n（２）平仮名「あ」は「安」の草体。片仮名「ア」は「阿」の行書体の偏。\n"],0,""],["足","あ","","",0,["あ 【足】\nあし。「―の音せず行かむ駒もが/万葉 3387」\n〔多く「足掻(アガ)き」「足結(アユイ)」など，複合した形で見られる〕\n"],1,""],["畔","あ","","",0,["あ 【畔・畦】\n田のあぜ。「営田(ツクダ)の―を離ち/古事記（上）」\n"],2,""],["畦","あ","","",0,["あ 【畔・畦】\n田のあぜ。「営田(ツクダ)の―を離ち/古事記（上）」\n"],2,""],["阿","あ","","",0,["あ 【阿】\n〔梵 a〕\n梵語の第一字母の音訳。\n⇔吽(ウン)\n→阿字\n→梵字\n"],3,""],["唖","あ","","",0,["あ [1] 【唖】\n話しことばが重度に障害された状態。話しことばをまったく，あるいは，ほとんど発することができない状態をいう。\n"],4,""],["吾","あ","","",0,["あ 【吾・我】 （代）\n〔上代語。中古以降は「わ」が用いられた〕\n一人称。わたし。あれ。「吾妹子に―が恋ひ死なば/万葉 3566」\n"],5,""],["我","あ","","",0,["あ 【吾・我】 （代）\n〔上代語。中古以降は「わ」が用いられた〕\n一人称。わたし。あれ。「吾妹子に―が恋ひ死なば/万葉 3566」\n"],5,""],["彼","あ","","",0,["あ 【彼】 （代）\n遠称の指示代名詞。あれ。「―はと見る淡路の島のあはれさへ/源氏（明石）」\n"],6,""],  ...
```

**Comment by LucasMIA** [comment]
It is your responsibility to make sure dictionaries are formatted appropriately to not cause issues. There are however a number of dictionaries you can find shared by the community that have already been appropriately converted to yomichan format, you may want to search "Yomichan mattvsjapan" on Youtube. Note that the Kanji dictionary and the frequency list for Yomichan do not work with the add-on.

**Comment by mariomeissner** [comment]
Importing the Sanseido dictionary from the source you pointed me to has the same issue: no entries are displayed when searching.

**Comment by LucasMIA** [comment]
Please message me on twitter if you feel you have found an issue and would like to troubleshoot. I have the sanseido dictionary working fine on my end and my guess is that your problem is more than likely user error.
