### ISSUE TITLE
Copying directly from the entry will preserve HTML formating

### ISSUE THREAD

**Issue by JiaChen-Zeng** [migaku-official/Migaku-Dictionary-Addon#15]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS: win 10
  - Anki: 2.1.20 (47a1bf8b)

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
After I update to Anki 2.1.20, it seems to have a new feature of preserving formating. But the kanji's light color is hard to see. I hope it can be pasted as raw text.
![image](https://user-images.githubusercontent.com/3676278/76767223-38afe280-67d4-11ea-99e5-837f05cd463a.png)

**Comment by LucasMIA** [comment]
Use ctrl+shift+v when pasting. Also which editor are you seeing the issue in?

**Comment by LucasMIA** [comment]
I tested and see what you mean, I will release a fix for this momentarily.

**Comment by JiaChen-Zeng** [comment]
<kbd>ctrl+shift+v</kbd> works for me. Thank you!
