### ISSUE TITLE
The header of dictionary window takes too much vertical space

### ISSUE THREAD

**Issue by JiaChen-Zeng** [migaku-official/Migaku-Dictionary-Addon#17]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Win 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
In Anki 2.1.20, it seems to have a new feature to set user interface size. I set it to 130%. When I let the window be half size of the screen, the header takes too much space.
![image](https://user-images.githubusercontent.com/3676278/76915641-ee745180-68f8-11ea-9ee9-6b45d239edac.png)

---
Until the window is 2/3 of the screen, the buttons don't break into 2 lines.
![image](https://user-images.githubusercontent.com/3676278/76915891-c5a08c00-68f9-11ea-86a2-aa5d6080c90a.png)

And to be honest, I think even in normal settings, the header is already too big.

**Comment by LucasMIA** [comment]
The scaling was implemented after this add-on was created, I don't plan to take my time to do anything about it as I have other higher priority projects going on at the moment. If you would like to see some change, feel free to open a pr and I can review it.
