### ISSUE TITLE
font size change missing

### ISSUE THREAD

**Issue by cocowash** [migaku-official/Migaku-Dictionary-Addon#18]
**Type:**
  - [ ] bug
  - [x] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS:

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
[It would be a great option if MIA Dictionary has the possibility to change the font size, specially for those whose have vision dysfunctionality (or otherwise want just a bigger font). It would be great that with control  + mouse scroll the words could become bigger to fit user necessities]

**Comment by LucasMIA** [comment]
You can already change the font size, please refer to the guide.
