### ISSUE TITLE
Error MIA Dictionary

### ISSUE THREAD

**Issue by Amzng24** [migaku-official/Migaku-Dictionary-Addon#19]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [] no

**Description:**
MIA Dictionary add-on worked fine for me, until a couple of days ago. I now get the following error when I want to open the add-on. Any thoughts?

[errors-mia-dictionary.txt](https://github.com/mass-immersion-approach/MIA-Dictionary-Addon/files/4401207/errors-mia-dictionary.txt)

**Comment by LucasMIA** [comment]
You're running an out of date version the add-on. Please update to Anki 2.1.20 - 2.1.22 and update the add-on.
