### ISSUE TITLE
Missing return from Reviewer._linkHandler breaks add-ons that depend on return value

### ISSUE THREAD

**Issue by glutanimate** [migaku-official/Migaku-Dictionary-Addon#20]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: all

**I'm going to open a PR to resolve the issue:**
  - [x] yes
  - [ ] no

**Description:**

Add-ons like Pop-up Dictionary depend on the link handler to pass values between JS and PY. Unfortunately MIA Dictionary currently does not return the return value of the original link handler, breaking that bridge.

cf.: https://github.com/ankitects/anki/pull/228 and https://github.com/ankitects/anki/commit/56e1643bfa0391c71d3323b7d12b77c9fa8af551

**Related bug report**

https://github.com/glutanimate/popup-dictionary/issues/39

**Comment by LucasMIA** [comment]
oopsie. ty.

**Comment by LucasMIA** [comment]
Actually now that I look at the source, it does not seem that _linkHandler returns anything? Why are you returning it?

from reviewer.py:

```def _linkHandler(self, url: str) -> None:
        if url == "ans":
            self._getTypedAnswer()
        elif url.startswith("ease"):
            self._answerCard(int(url[4:]))
        elif url == "edit":
            self.mw.onEditCurrent()
        elif url == "more":
            self.showContextMenu()
        elif url.startswith("play:"):
            play_clicked_audio(url, self.card)
        else:
            print("unrecognized anki link:", url)```

**Comment by glutanimate** [comment]
That's a fair point. This is definitely not obvious and the fact that it wasn't obvious was a fairly major oversight in earlier Anki releases (before the introduction of `webview_did_receive_js_message`). 

Basically, there is a super opaque return value chain that goes all the way back from _linkHandler to AnkiWebPage._bridge.cmd. _linkHandler and other bridge commands used in Anki can, but do not have to, return a value. If they do, the value gets passed back to a JS callback in `pycmd` (if specified). Pop-up Dictionary, for instance, extends _linkHandler with a return value to create a PY → JS bridge. So if Pop-up Dictionary monkey-patches _linkHandler first, another add-on patching _linkHandler without a return value will break that bridge.

It's a super easy compatibility trap to fall into (documented by all the related PRs regarding compat issues in https://github.com/ankitects/anki/pull/228 !), and I'm really glad that the new hook system finally solves it for the most part.

**Comment by LucasMIA** [comment]
So basically the issue is only with the compatibility with the other add-on then? I mean it's fine to make this change, but you should be clear in your communication about why it's happening. The truth is that under the current implementation not taking into account other add-ons that there was not a problem so you should not mark this issue as a 'bug', since that's inaccurate.

**Comment by glutanimate** [comment]
Sure, that's a fair assessment. Let's call it an Anki inconsistency causing an add-on incompatibility that we were able to fix through an add-on enhancement.
