### ISSUE TITLE
Pressing ctrl+c+space doesnt work in Linux

### ISSUE THREAD

**Issue by grenzionky** [migaku-official/Migaku-Dictionary-Addon#3]
**Type:**
  - [X] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Manjaro Linux x86_64
  - Kernel: 5.3.15-1-MANJARO 
  - WM: awesome 

**Description:**

I installed the addon and dictionaries exactly as the [tutorial video](https://www.youtube.com/watch?v=iKldS0JLVR0) said how to do it, and when I select a word in an external program, and press CTRL+C+SPACE, Anki opens up a popup with ↓ instead of the dictionary with the selected word.
```
Anki 2.1.15 (442df9d6) Python 3.8.0 Qt 5.13.2 PyQt 5.13.2
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons possibly involved: MIA Dictionary

Caught exception:
  File "/home/nitsi/.local/share/Anki2/addons21/1655992655/main.py", line 442, in captureKey
    mw.hkThread.handleSystemSearch()
  File "/home/nitsi/.local/share/Anki2/addons21/1655992655/midict.py", line 727, in handleSystemSearch
    self.search.emit(Pyperclip.paste())
  File "/home/nitsi/.local/share/Anki2/addons21/1655992655/Pyperclip.py", line 638, in lazy_load_stub_paste
    return paste()
  File "/home/nitsi/.local/share/Anki2/addons21/1655992655/Pyperclip.py", line 155, in paste_gtk
    clipboardContents = gtk.Clipboard().wait_for_text()
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 72, in __getattr__
    raise AttributeError(_static_binding_error)
<class 'AttributeError'>: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by LucasMIA** [comment]
Linux is not officially supported, so I don't plan on bug testing/fixing bugs for linux issues. If you or others wanted to open a pr to deal with any linux issues I would be open to merging any fixes you guys offer.

**Comment by fsmiamoto** [comment]
This problem seems to be with the Pyperclip code.

Found an [issue](https://github.com/asweigart/pyperclip/issues/106) on the module repo referring to this exact problem

Applying the changes of this [pull request](https://github.com/asweigart/pyperclip/pull/111) to the `src/Pyperclip.py` file has solved the problem for me.

Since these changes do not affect the supported operating systems, maybe merging #7 would be fine for further testing

**Enviroment:**
 - OS: Arch Linux x86_64
 - Kernel: 5.4.6-arch3-1

**Comment by grenzionky** [comment]
thanks! that fixed it!
