### ISSUE TITLE
Sanseido web dictionary support

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Dictionary-Addon#34]
**Type:**
  - [ ] bug
  - [ x] feature
  - [ ] enhancement
  - [ ] question

**I'm going to open a PR to resolve the issue:**
  - [ x] yes
  - [ ] no

**Description:**
The [sanseido web dictionary](https://www.sanseido.biz/) is a monolingual japanese web dictionary.

It provides concise definitions of words and seems to be useful for the monolingual transition, as can be seen in [this video](https://www.youtube.com/watch?v=AW-pw-EAMkY).

After some short testing it's results can be accessed with simple http requests (I tested it with curl).
I think it could be implemented in the MIA-Dictionary-Addon in a similar way to the google photos feature.

Would you accept a pull request if I would implement this?

**Comment by LucasMIA** [comment]
I can't guarantee when I will have time to review and merge the pull request but we would definitely take a look at it at some point if you were to open a pr. 👍

**Comment by MinmoTech** [comment]
I have only done some stuff for the integration until now, the code itself is simple, but as I have problems navigating the migaku dictionary codebase, I haven't finished it yet.

I have written this simple python script that takes a word as stdin and prints the definition to stdout which I'm using as a quick replacement right now, I hope someone will find it useful until I finish a proper integration: [Link to python script](https://github.com/juligreen/Configfiles/blob/master/Programs/sanseido.py)

**Comment by MinmoTech** [comment]
As the sanseido website does not exist anymore, we can close this issue
