### ISSUE TITLE
Monolingual japanese dictionary?

### ISSUE THREAD

**Issue by ghost** [migaku-official/Migaku-Dictionary-Addon#52]
**Type:**
  - [ ] question

**Environment:**
  - OS: Arch linux

**I'm going to open a PR to resolve the issue:**
  - [ ] no

**Description:**
Does a monolingual dictionary for japanese exist? Can it be manually added like the other ones?

**Comment by lostasock** [comment]
https://www.youtube.com/watch?v=5oxdPY9eH48

**Comment by ghost** [comment]
Thanks a lot!
