### ISSUE TITLE
Forvo/Google Images not showing up/Dictionary order remains unchanged (1.1.05, Anki 2.1.35)

### ISSUE THREAD

**Issue by joshuatants** [migaku-official/Migaku-Dictionary-Addon#55]
**Type:**
  - [ *] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Win 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [ *] no

**Description:**
1. i've switched the order of the dictionaries around several times in my dictionary group, but despite restarting anki etc, the order of the dicts remain unchanced
unchanged
2. i have forvo and google imagse selected, but they are not showing up in the lookup window

**Comment by WilsonNet** [comment]
I'm having the same issue.

**Comment by WilsonNet** [comment]
I was having the same issue, but you just need to select the Dictionary Group in the main dictionary window:

![image](https://user-images.githubusercontent.com/25280488/106083948-18db9180-60fc-11eb-97a0-a572b0951072.png)

**Comment by KieranBrannigan** [comment]
Looks like this issue has been solved, thanks @WilsonNet ! 

If you still have this issue you can comment below and we will reopen this issue.

Thank you for your continued support!
