### ISSUE TITLE
Redundant Dependencies

### ISSUE THREAD

**Issue by cofinley** [migaku-official/Migaku-Dictionary-Addon#8]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: All

**I'm going to open a PR to resolve the issue:**
  - [x] yes
  - [ ] no

**Description:**

There are several dependencies in the root space which are redundant:

- requests and bs4 are fulfilled by Anki [here](https://github.com/ankitects/anki/blob/4fc6184f800c2c8bcdd504b21af3ae4c1dcffcb4/pylib/setup.py#L17) and [here](https://github.com/ankitects/anki/blob/4fc6184f800c2c8bcdd504b21af3ae4c1dcffcb4/qt/setup.py#L30)
- urllib3 is fulfilled by requests [here](https://github.com/psf/requests/blob/d2590ee46c0641958b6d4792a206bd5171cb247d/setup.py#L47)

Dependencies should also have their own folder instead of sharing the root space with the other project files. This would include:

- `keyboardMac/`
- `linux/`
- `pynput/`
- `Pyperclip.py`

It looks like `six` isn't used(?)

This should help clean things up, reduce the addon payload, and help with future contributions :)

---

P.S. Great addon! Lot of work went into this. I'd like to help with PyQt and general refactoring/organizing if/when I have more free time. This project could really benefit from the use of Qt Designer and .ui files!

**Comment by LucasMIA** [comment]
Feel free to open pull requests with fixes to these issues, but refactoring pull requests should currently each be very limited in scope as I don't have time to read any large pull requests that would greatly change the current code structure, and am currently working on new features on my own private branch for future releases. So imo if you wish to refactor the code in some major way it would be best to wait until I am done working on all of this add-on's planned features (which will not be for some time, months at least). Also it's worth noting that this add-on has been through quite a few changes in design and you're seeing the end result of that process, I am sure there are more artifacts to still be found in many places. A final note is that this project never aspired to production level code/design, and I am well aware that it doesn't live up to that standard~. Besides that, thanks for offering to contribute!

**Comment by cofinley** [comment]
Yep, I hear ya loud and clear. I don't plan on changing much for those same reasons, just imports and some references. Mega-PRs usually introduce more confusion than change.

Can I ask why the private development? There are some good (addon) devs out there who could help expedite things and bring in ideas. Though, I understand if it aligns more with MIA's M.O..

Thanks for the quick response!

**Comment by LucasMIA** [comment]
About the private development, it's just our general development model, just like we don't announce new projects, we don't announce new features either. Everything is kept in house until release, whether that be in a beta form or public form. That way we can focus on our tasks without the distractions of deadlines or features not meeting their expectations. It's a much more comfortable development environment.
